### ISSUE TITLE
Color of masks

### ISSUE THREAD

**Issue by zifuwan** [microsoft/SoM#1]
Hi authors,

Thanks for the interesting work. Could you tell us how you treated the color of the masks for marking? Precisely, after outlining an object with a line, do you fill the mask with a light color? Besides, how did you choose the color for each numeric mark (the color of the number and the color of the background, since I noticed the color can be black and grey and other colors)?

Thanks.

**Comment by MaureenZOU** [comment]
The marker itself actually does not influence the performance. We select the number randomly and the background color is either black or white with the highest contrast with the font color. These selection are for visualization purpose.
