### ISSUE TITLE
SoM works with open-sourced multimodal LM?

### ISSUE THREAD

**Issue by j-min** [microsoft/SoM#13]
Impressive work 👍 

I'm interested if SoM works with open-sourced multimodal LMs such as LLaVA v1.5 as well. If you have tried this, can you share your experience on this?

**Comment by quantaji** [comment]
I have the same question too!

**Comment by abrichr** [comment]
There should not be any reason for the principles behind SoM to work with any LMM/VLM. This repository does not implement integrations with other models, but in principle it should be straightforward.
