### ISSUE TITLE
problem with api

### ISSUE THREAD

**Issue by qitanda** [microsoft/SoM#18]
how can i use it via api in order to get image with marks and get coordinate of marks?
i met a problem when i try to use gradio api
![2024-01-13 13-08-12屏幕截图](https://github.com/microsoft/SoM/assets/94268712/b446772c-2139-4f6b-a7d3-baf612923252)

**Comment by abrichr** [comment]
Possibly related: https://github.com/microsoft/SoM/issues/22

@qitanda can you please provide your client code?

Edit: fixed in https://github.com/microsoft/SoM/pull/19
