### ISSUE TITLE
Data for evaluation

### ISSUE THREAD

**Issue by leezythu** [microsoft/SoM#2]
The work is great!
I'd like to know where I can get the subset of datasets for evaluation used in the paper?

**Comment by jwyang** [comment]
glad you like it! We will release the evaluation datasets shortly this week!

**Comment by KainingYing** [comment]
Thanks for your great work. Look forward to data for evaluation.

**Comment by jwyang** [comment]
@leezythu, @KainingYing 

thanks again for your interest in our benchmark. Please find the first version of our SoM-Bench here: 

https://github.com/microsoft/SoM/tree/main/benchmark

Please note that we still working on the compilation of the ground-truth annotations for COCO, ADE20K and the automatic evaluation code now that GPT-4V API has been released. For now, you can try flickr30k and refcocog first.

thanks!

**Comment by KainingYing** [comment]
Great work! Thanks :)
