### ISSUE TITLE
Setup dockerfile

### ISSUE THREAD

**Issue by anandasaia** [microsoft/SoM#23]
Can someone please setup a docker setup for running SoM? Keeps running to a lot of compatibility issues for a lot of packages.

**Comment by abrichr** [comment]
@anandasaia thank you for creating this issue! Please see https://github.com/microsoft/SoM/pull/19 for a Dockerfile

Please note this needs to be built with `nvidia-docker`, as per https://github.com/microsoft/SoM/pull/19/files#diff-8859eb5563c8eb501f0b3889c89d1487713a1cbb09bcc6b2ad186d8da689b9f1R39. This requires the CUDA runtime. https://github.com/microsoft/SoM/pull/19 provides code to automatically deploy an EC2 instance with the necessary hardware capabilities:

```
# 1. Spin up an EC2 instance and create the workflow file
python deploy.py start

# 2. Connect to the EC2 instance
# github_actions_url and gradio_server_url will have been printed to console.
# Open github_actions_url in a browser and wait for the build to finish, then:
python client.py <gradio_server_url>

# 3. Terminate the EC2 instance
python deploy.py stop
```

Dockerfile: https://github.com/microsoft/SoM/pull/19/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

Step by step instructions: https://github.com/microsoft/SoM/pull/19#instructions

**Comment by abrichr** [comment]
Since https://github.com/microsoft/SoM/pull/19 was merged, I believe this can be closed as completed.
