### ISSUE TITLE
NameError when running the demo_som.py

### ISSUE THREAD

**Issue by TanZQ** [microsoft/SoM#27]
The environment is Ubutun system, and all environment deployment and package installation are normal.
When running demo_som.py in the last step, I got a NameError:
![截图 2024-04-09 17-32-41](https://github.com/microsoft/SoM/assets/40746943/ec7ab6ff-2b16-47c5-a1f7-18974e21d261)
The code part is here:
![图片](https://github.com/microsoft/SoM/assets/40746943/b723a7b1-f78f-48dd-8572-ddda69c8e23f)

The problem was solved, but new problems arose.
I found the distributed file and added a line in the import section：
from mpi4py import MPI
![图片](https://github.com/microsoft/SoM/assets/40746943/27e54d49-3511-4ffb-918a-50f184dcb982)
The NameError was successfully resolved.
But after continuing to run, a new error was reported again, this time it was the AttributeError in demo_som.py:
![图片](https://github.com/microsoft/SoM/assets/40746943/9a62cff0-a19a-4617-b922-830b7471bd55)
Looking forward for your help.

**Comment by 15186316** [comment]
<img width="1158" alt="微信图片_20240411190950" src="https://github.com/microsoft/SoM/assets/116073282/f8c77225-3ee2-4741-aa97-d9282139af48">
