### ISSUE TITLE
Increase the number of objects/elements detected

### ISSUE THREAD

**Issue by aakashb09** [microsoft/SoM#28]
In my testing, I found that some areas are not marked for mobile/website screenshots. Is there a way to get it to mark more things?

Would finetuning Detectron2 on a custom dataset suit my use case?

![IMG_4708](https://github.com/microsoft/SoM/assets/122796493/ffb51f23-d2a8-4f41-b3f2-169213442b7a)

**Comment by abrichr** [comment]
Make sure you are setting the granularity to the maximum value.

In https://github.com/OpenAdaptAI/OpenAdapt/pull/610 we had good results by fist segmenting the screenshot, and processing each segment individually before recombining.
