### ISSUE TITLE
Some notes on installation

### ISSUE THREAD

**Issue by taesiri** [microsoft/SoM#3]
Hello,

First of all, thank you for sharing the source code.

I encountered some issues while trying to install `Semantic-SAM` following the instructions in the `README` file. In the `Semantic-SAM` repository, there is a [pyproject.toml](https://github.com/UX-Decoder/Semantic-SAM/blob/main/pyproject.toml) file, and theoretically, it should take care of the installation. However, due to some strange issues, I had to install it manually.

Here are the steps I followed for anyone who is interested:

Using a fresh Anaconda environment to install Semantic-SAM:

```bash
pip3 install torch==1.13.1 torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cu113
python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'
pip install git+https://github.com/cocodataset/panopticapi.git
git clone https://github.com/UX-Decoder/Semantic-SAM
cd Semantic-SAM
python -m pip install -r requirements.txt
```

After this, you need to compile and install `MultiScaleDeformableAttention`:

```bash
git clone https://github.com/facebookresearch/Mask2Former
cd Mask2Former/mask2former/modeling/pixel_decoder/ops
sh make.sh
```

Additionally, you need to install `mpi4py`:

```bash
conda install -c conda-forge mpi4py
```

You can install SEEM and SAM using the pip+git method:

```bash
# Install SEEM
pip install git+https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git@package
# Install SAM
pip install git+https://github.com/facebookresearch/segment-anything.git
```

<img width="1549" alt="Screenshot 2023-10-23 at 5 52 30 PM" src="https://github.com/microsoft/SoM/assets/588431/b1e56635-c335-4225-aa93-cc6344e644e9">

I hope this helps resolve any installation issues.

**Comment by jwyang** [comment]
Hi, @taesiri, really appreciate for your instruction to install the package! This is very useful, I will go to handle the inconvenience of installation.

Best.
Jianwei

**Comment by jwyang** [comment]
Already fixed, closing this issue.

**Comment by dddraxxx** [comment]
> Hello,
> 
> First of all, thank you for sharing the source code.
> 
> I encountered some issues while trying to install `Semantic-SAM` following the instructions in the `README` file. In the `Semantic-SAM` repository, there is a [pyproject.toml](https://github.com/UX-Decoder/Semantic-SAM/blob/main/pyproject.toml) file, and theoretically, it should take care of the installation. However, due to some strange issues, I had to install it manually.
> 
> Here are the steps I followed for anyone who is interested:
> 
> Using a fresh Anaconda environment to install Semantic-SAM:
> 
> ```shell
> pip3 install torch==1.13.1 torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cu113
> python -m pip install 'git+https://github.com/MaureenZOU/detectron2-xyz.git'
> pip install git+https://github.com/cocodataset/panopticapi.git
> git clone https://github.com/UX-Decoder/Semantic-SAM
> cd Semantic-SAM
> python -m pip install -r requirements.txt
> ```
> 
> After this, you need to compile and install `MultiScaleDeformableAttention`:
> 
> ```shell
> git clone https://github.com/facebookresearch/Mask2Former
> cd Mask2Former/mask2former/modeling/pixel_decoder/ops
> sh make.sh
> ```
> 
> Additionally, you need to install `mpi4py`:
> 
> ```shell
> conda install -c conda-forge mpi4py
> ```
> 
> You can install SEEM and SAM using the pip+git method:
> 
> ```shell
> # Install SEEM
> pip install git+https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git@package
> # Install SAM
> pip install git+https://github.com/facebookresearch/segment-anything.git
> ```
> 
> <img alt="Screenshot 2023-10-23 at 5 52 30 PM" width="1549" src="https://user-images.githubusercontent.com/588431/277506734-b1e56635-c335-4225-aa93-cc6344e644e9.png">
> I hope this helps resolve any installation issues.

It is weired but I encountered "NameError: name 'MPI' is not defined" for SEEM package and need to add "from mpi4py import MPI" in that file

**Comment by taesiri** [comment]
@dddraxxx Have you installed `mpi4py`?

```
conda install -c conda-forge mpi4py
```

**Comment by dddraxxx** [comment]
> @dddraxxx Have you installed `mpi4py`?
> 
> ```
> conda install -c conda-forge mpi4py
> ```

yes, but still need to import that in the 'seem' library code

**Comment by taesiri** [comment]
@dddraxxx You should check and verify if `mpi4py` and `openmpi` are installed.

Btw,  I can share my `environment.yaml` file if you think that can help.

**Comment by dddraxxx** [comment]
@taesiri yes. I installed both via conda and the code can run well if I add that line `from mpi4py import MPI`.

**Comment by wentaoyuan** [comment]
I had the same issue with MPI. It seems that
`pip install git+https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git@package`
installs the `package` branch of the SEEM repo which is not fully in sync with `v1.0` branch.
Thus, `utils/distributed.py` is missing an import statement at line 7: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/7b2e76dbb17d0b7831c6813a921fe2bc8de22926/utils/distributed.py#L7.

**Comment by NoOneUST** [comment]
> I had the same issue with MPI. It seems that `pip install git+https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git@package` installs the `package` branch of the SEEM repo which is not fully in sync with `v1.0` branch. Thus, `utils/distributed.py` is missing an import statement at line 7: https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once/blob/7b2e76dbb17d0b7831c6813a921fe2bc8de22926/utils/distributed.py#L7.

I also met the same problem. How did you solve it?

**Comment by abrichr** [comment]
See https://github.com/microsoft/SoM/issues/12#issuecomment-1930432657 for an explanation and fix.
