### ISSUE TITLE
NameError: name 'MPI' is not defined

### ISSUE THREAD

**Issue by RandyWangRaining** [microsoft/SoM#34]
my mpi is ok
when i input mpirun -n 4 python3 owntest.py 
i get My rank is  0
My rank is  1
My rank is  2
My rank is  3

but when i run  :python demo_som.py
get:

File "/home/randywang/anaconda3/envs/som2/lib/python3.10/site-packages/seem/utils/distributed.py", line 61, in init_distributed
    apply_distributed(opt)
  File "/home/randywang/anaconda3/envs/som2/lib/python3.10/site-packages/seem/utils/distributed.py", line 20, in apply_distributed
    master_address = MPI.COMM_WORLD.bcast(master_address, root=0)
NameError: name 'MPI' is not defined

**Comment by abrichr** [comment]
Related: https://github.com/microsoft/SoM/issues/12#issuecomment-1930432657

Try:
```
pip install git+https://github.com/UX-Decoder/Segment-Everything-Everywhere-All-At-Once.git@33f2c898fdc8d7c95dda014a4b9ebe4e413dbb2b 

pip install mpi4py
```

**Comment by RandyWangRaining** [comment]
I soved this problem by  adding 
import mpi 
in /home/anaconda3/envs/som2/lib/python3.10/site-packages/seem/utils/distributed.py"
