### ISSUE TITLE
Schedule of Dataset Releasing

### ISSUE THREAD

**Issue by HenryHZY** [microsoft/SoM#4]
Hi @jwyang , do you have a schedule to release the dataset? Thanks for your great project!

**Comment by jwyang** [comment]
Thanks for your interest! We will release the dataset tomorrow!

**Comment by HenryHZY** [comment]
Got it. Thanks for your quick reply!

**Comment by jwyang** [comment]
Hi, @HenryHZY, 

thanks again for your interest. Please find the first version of our SoM-Bench here: 

https://github.com/microsoft/SoM/tree/main/benchmark

Please note that we still working on the compilation of the ground-truth annotations for COCO, ADE20K and the automatic evaluation code now that GPT-4V API has been released. For now, you can try flickr30k and refcocog first.

thanks!

**Comment by HenryHZY** [comment]
Hi @jwyang
Thanks for the detailed update of the datasets and task prompts! 
I have tested some of the examples in the paper previously and found that GPT-4V+SoM didn't work particularly well. But it did get better with the addition of some prompts about "numberic ID". 
And I just find that Benchmark Readme also provides a "language prompt" for a specific task, which is reasonable and important for SoM prompting.
Thanks again. I think we can close this issue now:)
