### ISSUE TITLE
How can we use SoM for video segmentation

### ISSUE THREAD

**Issue by QinghongLin** [microsoft/SoM#6]
Hi, thanks for the awesome works!
 wondering have you provided any codes or instructions about how to use SoM for video segmentation or tracking?

**Comment by jwyang** [comment]
thanks for your interest! We are going to release all evaluation scripts for the tasks in our paper very soon!

**Comment by QinghongLin** [comment]
Thanks for response, btw, I meet such error regarding MPI, have you meet it in previously :D

```
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[cr1-p4de24xlarge-2:367084] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed
```

**Comment by jwyang** [comment]
I think you can skip this MPI installation, we intended to remove the dependencies on MPI but please let me know if it does not work without MPI.

**Comment by QinghongLin** [comment]
It happen when I run `demo_som.py`, I think it caused by seem. If want to skip this, can you point out which rows I should comment.

**Comment by jwyang** [comment]
got it, let me try to figure it out.

**Comment by jwyang** [comment]
Hi, @QinghongLin, had just remove the dependencies on MPI for SEEM, can you install seem again and see whether it works?

**Comment by QinghongLin** [comment]
Thanks for the update! after I remove the:`# opt_seem = init_distributed_seem(opt_seem)` in line 49 and , it can work now.

**Comment by QinghongLin** [comment]
Hi @jwyang , Thanks for the update! I removed the:
opt_seem = init_distributed_seem(opt_seem) in line 49 of demo_som.py
and replace the `state_dict = torch.load(load_dir, map_location=self.opt['device'])`
as
`state_dict = torch.load(load_dir, map_location='cpu')`

it can work. Thanks  a lot!

**Comment by jwyang** [comment]
awesome!

**Comment by abrichr** [comment]
See https://github.com/microsoft/SoM/issues/12#issuecomment-1930432657 for an explanation and fix for the MPI issue.
