### ISSUE TITLE
Latency Issue

### ISSUE THREAD

**Issue by bjohn22** [microsoft/SoM#7]
I tested the demo and it works (i use default parameters). I got better output when I modified the prompt template in `gpt4v.py`. The key issue for me is the latency. It took about 4-5 minutes to inference on the image after clicking on Run. 
It then took additional 6 -8 minutes to get response from GPT4-V after clicking on 'Submit". Any thought on how I can improve this processing time?

I work in WSL2 environment equipped with Nvidia rtx 3090.

**Comment by jwyang** [comment]
Hi, @bjohn22 , given that it took 4-5min to inference on an image, I guess you are using CPU but would suggest use GPU for the inference, which may only take 2sec. Regarding the second part, it usually took me 3secs to get the GPT-4V response,

**Comment by abrichr** [comment]
Inference on EC2 with https://github.com/microsoft/SoM/pull/19 takes about 3-5s/image.
