### ISSUE TITLE
A question about grayscale image

### ISSUE THREAD

**Issue by HenryHZY** [microsoft/SoM#8]
Hi @jwyang 
I tested SoM+SAM with a script:
```
from PIL import Image
image = Image.open("gray.jpg")
output, mask = inference_sam_m2m_auto(model, image, text_size, label_mode, alpha, anno_mode)
image = Image.fromarray(output)
image.save("gray-som.jpg")
```
Running the script will throw some erros about image channel (e.g., image.shape[2]).
It seems that SoM+SAM tool doesn't support grayscale image currently.
Is there a mistake in my usage? 

Does directly modifying some code to support grayscale maps affect the performance of SoM+SAM? For example:
```
image = image.convert('RGB')
```

**Comment by jwyang** [comment]
Hi, @HenryHZY, yes, adding the conversion line is a way of addressing the issue.

**Comment by HenryHZY** [comment]
Thanks a lot.
